/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as AuthedTasksRouteImport } from './routes/_authed.tasks'
import { Route as AuthedReviewRouteImport } from './routes/_authed.review'
import { Route as AuthedHabitsRouteImport } from './routes/_authed.habits'
import { Route as AuthedChatRouteImport } from './routes/_authed.chat'
import { Route as AuthedNotebooksIndexRouteImport } from './routes/_authed.notebooks.index'
import { Route as AuthedSettingsProfileRouteImport } from './routes/_authed.settings.profile'
import { Route as AuthedNotebooksNotebookIdRouteImport } from './routes/_authed.notebooks.$notebookId'
import { Route as AuthedSettingsWorkspaceNewRouteImport } from './routes/_authed.settings.workspace.new'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTasksRoute = AuthedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReviewRoute = AuthedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHabitsRoute = AuthedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChatRoute = AuthedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotebooksIndexRoute = AuthedNotebooksIndexRouteImport.update({
  id: '/notebooks/',
  path: '/notebooks/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsProfileRoute = AuthedSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotebooksNotebookIdRoute =
  AuthedNotebooksNotebookIdRouteImport.update({
    id: '/notebooks/$notebookId',
    path: '/notebooks/$notebookId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedSettingsWorkspaceNewRoute =
  AuthedSettingsWorkspaceNewRouteImport.update({
    id: '/settings/workspace/new',
    path: '/settings/workspace/new',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/sign-in': typeof SignInRoute
  '/chat': typeof AuthedChatRoute
  '/habits': typeof AuthedHabitsRoute
  '/review': typeof AuthedReviewRoute
  '/tasks': typeof AuthedTasksRoute
  '/notebooks/$notebookId': typeof AuthedNotebooksNotebookIdRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
  '/notebooks/': typeof AuthedNotebooksIndexRoute
  '/settings/workspace/new': typeof AuthedSettingsWorkspaceNewRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/chat': typeof AuthedChatRoute
  '/habits': typeof AuthedHabitsRoute
  '/review': typeof AuthedReviewRoute
  '/tasks': typeof AuthedTasksRoute
  '/': typeof AuthedIndexRoute
  '/notebooks/$notebookId': typeof AuthedNotebooksNotebookIdRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
  '/notebooks': typeof AuthedNotebooksIndexRoute
  '/settings/workspace/new': typeof AuthedSettingsWorkspaceNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authed/chat': typeof AuthedChatRoute
  '/_authed/habits': typeof AuthedHabitsRoute
  '/_authed/review': typeof AuthedReviewRoute
  '/_authed/tasks': typeof AuthedTasksRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/notebooks/$notebookId': typeof AuthedNotebooksNotebookIdRoute
  '/_authed/settings/profile': typeof AuthedSettingsProfileRoute
  '/_authed/notebooks/': typeof AuthedNotebooksIndexRoute
  '/_authed/settings/workspace/new': typeof AuthedSettingsWorkspaceNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/chat'
    | '/habits'
    | '/review'
    | '/tasks'
    | '/notebooks/$notebookId'
    | '/settings/profile'
    | '/notebooks/'
    | '/settings/workspace/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/chat'
    | '/habits'
    | '/review'
    | '/tasks'
    | '/'
    | '/notebooks/$notebookId'
    | '/settings/profile'
    | '/notebooks'
    | '/settings/workspace/new'
  id:
    | '__root__'
    | '/_authed'
    | '/sign-in'
    | '/_authed/chat'
    | '/_authed/habits'
    | '/_authed/review'
    | '/_authed/tasks'
    | '/_authed/'
    | '/_authed/notebooks/$notebookId'
    | '/_authed/settings/profile'
    | '/_authed/notebooks/'
    | '/_authed/settings/workspace/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks': {
      id: '/_authed/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthedTasksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/review': {
      id: '/_authed/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthedReviewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/habits': {
      id: '/_authed/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthedHabitsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chat': {
      id: '/_authed/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthedChatRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notebooks/': {
      id: '/_authed/notebooks/'
      path: '/notebooks'
      fullPath: '/notebooks/'
      preLoaderRoute: typeof AuthedNotebooksIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/profile': {
      id: '/_authed/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthedSettingsProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notebooks/$notebookId': {
      id: '/_authed/notebooks/$notebookId'
      path: '/notebooks/$notebookId'
      fullPath: '/notebooks/$notebookId'
      preLoaderRoute: typeof AuthedNotebooksNotebookIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/workspace/new': {
      id: '/_authed/settings/workspace/new'
      path: '/settings/workspace/new'
      fullPath: '/settings/workspace/new'
      preLoaderRoute: typeof AuthedSettingsWorkspaceNewRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedChatRoute: typeof AuthedChatRoute
  AuthedHabitsRoute: typeof AuthedHabitsRoute
  AuthedReviewRoute: typeof AuthedReviewRoute
  AuthedTasksRoute: typeof AuthedTasksRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedNotebooksNotebookIdRoute: typeof AuthedNotebooksNotebookIdRoute
  AuthedSettingsProfileRoute: typeof AuthedSettingsProfileRoute
  AuthedNotebooksIndexRoute: typeof AuthedNotebooksIndexRoute
  AuthedSettingsWorkspaceNewRoute: typeof AuthedSettingsWorkspaceNewRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedChatRoute: AuthedChatRoute,
  AuthedHabitsRoute: AuthedHabitsRoute,
  AuthedReviewRoute: AuthedReviewRoute,
  AuthedTasksRoute: AuthedTasksRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedNotebooksNotebookIdRoute: AuthedNotebooksNotebookIdRoute,
  AuthedSettingsProfileRoute: AuthedSettingsProfileRoute,
  AuthedNotebooksIndexRoute: AuthedNotebooksIndexRoute,
  AuthedSettingsWorkspaceNewRoute: AuthedSettingsWorkspaceNewRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
