/**
 * TanStack Router instance for the SPA.
 *
 * The route tree is auto-generated by `@tanstack/router-plugin` (configured in
 * `vite.config.ts`) from the files under `src/routes/` and emitted to
 * `src/routeTree.gen.ts`. This module creates the single router instance used
 * by `<RouterProvider>` in `src/main.tsx` and registers the instance type with
 * `@tanstack/react-router` via module augmentation so that navigation helpers
 * (`Link`, `useNavigate`, `useParams`, etc.) are fully typed throughout the app.
 */
import { createRouter } from '@tanstack/react-router'

import { queryClient } from '@/lib/queryClient'
import { routeTree } from './routeTree.gen'

export type { RouterContext } from '@/lib/routerContext'

export const router = createRouter({
  routeTree,
  defaultPreload: 'intent',
  defaultPreloadStaleTime: 30_000,
  context: {
    queryClient,
  },
})

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}
